export const COUNTRY_FLAGS: Record<string, string> = {
  ghana: "🇬🇭",
  nigeria: "🇳🇬",
  kenya: "🇰🇪",
  "south africa": "🇿🇦",
  jamaica: "🇯🇲",
  india: "🇮🇳",
  philippines: "🇵🇭",
  thailand: "🇹🇭",
  uae: "🇦🇪",
  "united arab emirates": "🇦🇪",
  canada: "🇨🇦",
  australia: "🇦🇺",
  "united kingdom": "🇬🇧",
  uk: "🇬🇧",
  britain: "🇬🇧",
  england: "🇬🇧",
  usa: "🇺🇸",
  "united states": "🇺🇸",
  america: "🇺🇸",
  brazil: "🇧🇷",
  china: "🇨🇳",
  singapore: "🇸🇬",
  malaysia: "🇲🇾",
  pakistan: "🇵🇰",
  bangladesh: "🇧🇩",
  "sri lanka": "🇱🇰",
  ethiopia: "🇪🇹",
  tanzania: "🇹🇿",
  uganda: "🇺🇬",
  cameroon: "🇨🇲",
  zimbabwe: "🇿🇼",
  zambia: "🇿🇲",
  botswana: "🇧🇼",
  senegal: "🇸🇳",
  "trinidad and tobago": "🇹🇹",
  trinidad: "🇹🇹",
  barbados: "🇧🇧",
  guyana: "🇬🇾",
  "ivory coast": "🇨🇮",
  "côte d'ivoire": "🇨🇮",
};

export const COUNTRY_FACTS: Record<string, string[]> = {
  ghana: [
    "Mobile money accounts in Ghana outnumber bank accounts — MoMo and Vodafone Cash move billions in daily transfers.",
    "Ghanaians abroad send over £300 million home each year — more than most foreign aid the country receives.",
    "Dual citizens must enter and leave Ghana on a Ghanaian passport — your UK or US passport alone won't pass immigration.",
    "Ghana's land title registration can take 2–5 years without knowing which specific office to go to first.",
    "Ghana abolished the death penalty in 2023, becoming the first Anglophone West African country to do so.",
  ],
  nigeria: [
    "Nigeria receives over $20 billion in remittances each year — the highest in Africa and among the highest globally.",
    "The naira lost over 70% of its value against the dollar between 2022 and 2024 — the timing of a transfer matters more than the fee.",
    "Nigeria's NIN (National Identification Number) is now required for banking, SIM registration, and most government services.",
    "Lagos alone generates roughly 25% of Nigeria's entire GDP.",
    "Nigeria has two stock exchanges — yet fewer than 1% of diaspora Nigerians have ever invested through them from abroad.",
  ],
  kenya: [
    "M-Pesa handles transactions worth roughly 80% of Kenya's GDP every year — no other country's mobile money system comes close.",
    "Kenyan dual nationals must enter and leave Kenya on their Kenyan passport — no exceptions for any other citizenship.",
    "Kenya's Huduma Namba is required for property ownership, banking, and most formal services — getting one from abroad has specific steps.",
    "Kenya abolished stamp duty on home purchases under KES 3 million in 2023 — a change most returning diaspora members don't know about.",
    "Nairobi has more funded tech startups per capita than any other city in Africa.",
  ],
  "south africa": [
    "South Africans are limited to taking R1 million abroad per year without a tax clearance certificate from SARS.",
    "SARS taxes South African tax residents on their worldwide income — including money kept in foreign accounts.",
    "Property title transfers in South Africa take 3–6 months even under normal market conditions.",
    "A South African retirement annuity can only be accessed as a lump sum after formal emigration is recognised by SARB.",
    "South Africa's rand is one of the most traded emerging-market currencies globally, with significant daily swings.",
  ],
  jamaica: [
    "Jamaica receives over $3 billion in remittances annually — close to 20% of the country's entire GDP.",
    "Land disputes are one of Jamaica's most common legal problems — many properties have had no formal title for generations.",
    "Jamaica's NIS contributions can be made voluntarily from abroad — a pension option most diaspora Jamaicans don't know exists.",
    "USD is widely accepted in Jamaica, but all official government transactions must be paid in Jamaican dollars.",
    "Jamaica has one of the highest rates of informal property ownership in the Caribbean — common, but legally complicated on resale.",
  ],
  india: [
    "India receives more in remittances than any other country in the world — over $120 billion annually.",
    "NRIs must hold specific account types — NRE, NRO, or FCNR — each with entirely different tax and repatriation rules.",
    "Buying property in India as an NRI is permitted, but selling and repatriating the proceeds carries strict conditions that surprise most buyers.",
    "Indian inheritance law varies by religion — Hindu, Muslim, and Christian succession rules are completely different legal frameworks.",
    "The Indian Rupee is a controlled currency — you cannot freely carry it in or out of India above set limits.",
  ],
  philippines: [
    "The Philippines receives over $36 billion in remittances annually — nearly 9% of the country's GDP.",
    "Foreigners and dual nationals cannot own land freehold in the Philippines — only condominiums up to 49% of a building.",
    "OFWs have a dedicated government agency — OWWA — with specific benefits unavailable to ordinary citizens, including legal aid abroad.",
    "Filipinos abroad can vote in presidential elections from overseas — a provision relatively rare among developing nations.",
    "The SRRV (Special Resident Retiree's Visa) allows long-term residency for returnees — but the rules are updated frequently.",
  ],
  thailand: [
    "Foreigners cannot own land freehold in Thailand — only condominiums, and only up to 49% of a building by foreign ownership.",
    "Thailand's Elite Visa offers 5–20 year residency for a one-time fee — with specific eligibility requirements most expats haven't checked.",
    "Thailand taxes foreign income if it is brought into the country in the same calendar year it was earned.",
    "Opening a Thai bank account as a foreigner requires a Non-Immigrant Visa — tourist visa holders are typically rejected.",
    "Thailand has no capital gains tax on property — but transfer fees and withholding tax at point of sale catch many expats off-guard.",
  ],
  uae: [
    "The UAE has no personal income tax — but establishing tax residency there still requires proof you've left your home country's tax system.",
    "A UAE residence visa is tied to employment or property — if you leave your job, you typically have 30 days before the visa expires.",
    "UAE Golden Visas now have expanded eligibility — many long-term expats qualify for 10-year residency without knowing it.",
    "Foreigners can own property freehold in the UAE in designated zones — but the rules differ between Dubai, Abu Dhabi, and other emirates.",
    "Some UAE banks will open accounts for non-residents — but the documentation required is very specific.",
  ],
  "united arab emirates": [
    "The UAE has no personal income tax — but establishing tax residency there still requires proof you've left your home country's tax system.",
    "A UAE residence visa is tied to employment or property — if you leave your job, you typically have 30 days before the visa expires.",
    "UAE Golden Visas now have expanded eligibility — many long-term expats qualify for 10-year residency without knowing it.",
    "Foreigners can own property freehold in the UAE in designated zones — but the rules differ between Dubai, Abu Dhabi, and other emirates.",
    "Some UAE banks will open accounts for non-residents — but the documentation required is very specific.",
  ],
  canada: [
    "Canada taxes residents on worldwide income — including money held in overseas accounts that was never brought into Canada.",
    "A Canadian Permanent Resident can lose their status by spending more than 2.5 years outside Canada in any 5-year period.",
    "The First Home Savings Account (FHSA), launched in 2023, is unknown to most recent immigrants — it offers up to $40,000 in tax-deductible savings.",
    "Canadian pension credits (CPP) can be transferred under social security agreements with over 60 countries.",
    "Bringing more than CAD 10,000 in or out of Canada must be declared at the border — failure to do so can lead to seizure.",
  ],
  australia: [
    "Australia's tax residency rules are among the most complex in the world — you can remain an Australian tax resident even while living abroad.",
    "Superannuation (Australia's pension) cannot be accessed until preservation age — even if you leave the country permanently.",
    "Foreign buyers pay an additional stamp duty surcharge of 7–8% on Australian property purchases in most states.",
    "Australia's HECS student debt became legally recoverable from Australians overseas in 2022 — a change many graduates abroad don't know about.",
    "Australia allows dual citizenship with most countries, but some nations require you to renounce others — always check both sides.",
  ],
  uk: [
    "HMRC can tax UK tax residents on income earned anywhere in the world — even money never brought back to Britain.",
    "National Insurance contributions can be topped up voluntarily from abroad — often worth thousands of pounds in additional state pension.",
    "The UK Settled Status scheme closed in June 2021 — EU citizens who missed it may have permanently lost their residency rights.",
    "A British passport currently offers visa-free access to over 190 countries — among the most powerful travel documents in the world.",
    "UK inheritance tax applies to your worldwide estate if you're domiciled in the UK — even assets held entirely overseas.",
  ],
  "united kingdom": [
    "HMRC can tax UK tax residents on income earned anywhere in the world — even money never brought back to Britain.",
    "National Insurance contributions can be topped up voluntarily from abroad — often worth thousands of pounds in additional state pension.",
    "The UK Settled Status scheme closed in June 2021 — EU citizens who missed it may have permanently lost their residency rights.",
    "A British passport currently offers visa-free access to over 190 countries — among the most powerful travel documents in the world.",
    "UK inheritance tax applies to your worldwide estate if you're domiciled in the UK — even assets held entirely overseas.",
  ],
  _default: [
    "Remittances to developing countries total over $600 billion annually — three times more than all foreign aid combined.",
    "Over 280 million people live outside their country of birth — the global diaspora is larger than the population of Brazil.",
    "The biggest hidden cost in international transfers is usually the exchange rate margin, not the fee shown on screen.",
    "Most countries have double taxation treaties — meaning you may not owe tax in two places on the same income.",
    "Over 50 countries now recognise dual citizenship — and the number has grown significantly in the last decade.",
  ],
};

export function getCountryFlag(countryInput: string): string {
  const key = countryInput.toLowerCase().trim();
  return COUNTRY_FLAGS[key] ?? "";
}

export function getCountryFacts(countryInput: string): string[] {
  const key = countryInput.toLowerCase().trim();
  return COUNTRY_FACTS[key] ?? COUNTRY_FACTS._default;
}
