export const MOCK_OPPORTUNITIES = [
  {
    keyword: "how to stop debt collectors calling",
    niche: "personal finance",
    country: "US",
    searchVolume: 74000,
    opportunityScore: 94,
    competition: "low",
    trend: "rising",
    easeToSell: "easy",
    minPrice: 9.97,
    maxPrice: 24.97,
    emotionalIntent: "fear",
    exactQuestions: JSON.stringify([
      "how to stop debt collectors from calling",
      "can debt collectors call at night",
      "how to make debt collectors stop harassing me",
      "what to say to debt collectors to stop calls",
      "debt collector won't stop calling what can I do",
    ]),
  },
  {
    keyword: "how to pass WAEC maths fast",
    niche: "education",
    country: "NG",
    searchVolume: 49000,
    opportunityScore: 91,
    competition: "low",
    trend: "rising",
    easeToSell: "easy",
    minPrice: 7.97,
    maxPrice: 19.97,
    emotionalIntent: "urgency",
    exactQuestions: JSON.stringify([
      "how to pass WAEC maths without reading",
      "WAEC maths topics that always come out",
      "fastest way to pass WAEC maths exam",
      "how to score A in WAEC mathematics",
      "WAEC maths past questions and answers",
    ]),
  },
  {
    keyword: "how to lose belly fat fast at home",
    niche: "health & fitness",
    country: "US",
    searchVolume: 165000,
    opportunityScore: 87,
    competition: "medium",
    trend: "stable",
    easeToSell: "easy",
    minPrice: 9.97,
    maxPrice: 29.97,
    emotionalIntent: "desire",
    exactQuestions: JSON.stringify([
      "how to lose belly fat in 2 weeks",
      "exercises to lose belly fat fast at home for beginners",
      "how to get rid of lower belly fat",
      "foods that burn belly fat overnight",
      "why can't I lose belly fat no matter what I do",
    ]),
  },
  {
    keyword: "why do I keep failing job interviews",
    niche: "career",
    country: "US",
    searchVolume: 33000,
    opportunityScore: 89,
    competition: "low",
    trend: "rising",
    easeToSell: "easy",
    minPrice: 12.97,
    maxPrice: 27.97,
    emotionalIntent: "pain",
    exactQuestions: JSON.stringify([
      "why do I always fail job interviews",
      "what am I doing wrong in interviews",
      "how to stop failing interviews",
      "interview mistakes that cost you the job",
      "why don't I get called back after interviews",
    ]),
  },
  {
    keyword: "how to sleep when anxious",
    niche: "mental health",
    country: "US",
    searchVolume: 58000,
    opportunityScore: 92,
    competition: "low",
    trend: "rising",
    easeToSell: "easy",
    minPrice: 9.97,
    maxPrice: 19.97,
    emotionalIntent: "fear",
    exactQuestions: JSON.stringify([
      "how to fall asleep when anxious and overthinking",
      "what to do when anxiety keeps you awake",
      "how to calm anxiety at night naturally",
      "why does anxiety get worse at night",
      "how to stop anxious thoughts before bed",
    ]),
  },
  {
    keyword: "how to start a business with no money",
    niche: "entrepreneurship",
    country: "US",
    searchVolume: 110000,
    opportunityScore: 83,
    competition: "medium",
    trend: "stable",
    easeToSell: "medium",
    minPrice: 14.97,
    maxPrice: 34.97,
    emotionalIntent: "desire",
    exactQuestions: JSON.stringify([
      "how to start a business with no money or experience",
      "businesses you can start with zero capital",
      "how to make money when you have nothing",
      "how to start online business from scratch with no money",
      "real ways to start a business broke",
    ]),
  },
  {
    keyword: "how to fix bad credit fast",
    niche: "personal finance",
    country: "US",
    searchVolume: 88000,
    opportunityScore: 90,
    competition: "low",
    trend: "rising",
    easeToSell: "easy",
    minPrice: 14.97,
    maxPrice: 29.97,
    emotionalIntent: "pain",
    exactQuestions: JSON.stringify([
      "how to fix bad credit score quickly",
      "how long does it take to fix bad credit",
      "how to remove negative items from credit report",
      "what raises credit score fast",
      "how to get a loan with bad credit",
    ]),
  },
  {
    keyword: "how to stop procrastinating",
    niche: "productivity",
    country: "US",
    searchVolume: 74000,
    opportunityScore: 78,
    competition: "medium",
    trend: "stable",
    easeToSell: "medium",
    minPrice: 9.97,
    maxPrice: 19.97,
    emotionalIntent: "confusion",
    exactQuestions: JSON.stringify([
      "why do I procrastinate even when I want to do things",
      "how to stop procrastinating and start working",
      "how to motivate yourself to stop procrastinating",
      "techniques to overcome procrastination",
      "why am I so bad at starting tasks",
    ]),
  },
];
